### ISSUE TITLE
Epic: Manage AWS IoT Devices, LoRaWAN Devices and Edge Devices

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1783]
## Description

IoT Hub Portal should use AWS as an IoT provider, alongside Azure.

## Acceptance criteria

- [ ] Manage AWS IoT Devices
- [ ] Manage AWS IoT LoRaWAN Devices
- [ ] Manage AWS IoT Edge Devices
