### ISSUE TITLE
Story: As a user, I want to manage IoT devices on AWS

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1866]
Feature: #1784

## Description

Like in Azure IoT Hub, users have to manage devices in the portal.

In AWS IoT Core, you can set properties on devices using the AWS IoT Device Shadow service. The device shadow is a virtual representation of your device's state in the cloud, and it allows you to interact with your devices even when they are offline or not connected to the internet. Currently, there is a one-ot-many relationship between a device and multiples shadow devices.

To set properties on devices in AWS IoT Core, you can follow these steps:

* Create a device shadow: Start by creating a device shadow for your device in AWS IoT Core. You can do this by using the AWS IoT SDKs or the AWS IoT Core Console.

* Define the desired state: The desired state is the state that you want your device to be in. You can define the desired state by creating a JSON document that includes the properties you want to set, and then updating the device shadow with this document.

* Update the device shadow: To update the device shadow, you can use the AWS IoT SDKs or the AWS IoT Core Console. You will need to provide the name of the device shadow and the JSON document containing the desired state.

* Synchronize the device shadow: Once you have updated the device shadow, you will need to synchronize it with the device. This can be done automatically by the AWS IoT Device SDKs or manually by sending a request to the device to retrieve the updated shadow.

By following these steps, you can set properties on your devices in AWS IoT Core and ensure that they are always in the desired state, even when they are offline or not connected to the internet.

## Acceptance criteria

- [x] User can CRUD devices based on existing device model
- [x] User can search across devices in the portal
- [x] User can set properties on devices on the device shadow

### Tasks

- [x] #1845
- [x] #1921
- [x] #1922
- [x] #1923
- [x] #1924
