### ISSUE TITLE
Story: As a user, I want to manage devices in groups

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1867]
## Description

This will allow me to streamline my device management process and improve my ability to make data-driven decisions.

## Acceptance criteria

- [ ] User can manage all device groups
- [ ] Device groups are hierarchic

### Tasks

- [ ] #1794
- [ ] #1795
- [ ] #1797
- [ ] #1796
- [ ] Task: Add group support on Azure Device Twins
