### ISSUE TITLE
Story: As a user, I want to manage IoT edge devices models on AWS

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1957]
This US is part of feature #1878

## Description

Like in Azure IoT Hub, users have to manage Edge Device models in the portal. 

## Acceptance criteria

- [ ] Edge Models should create AWS GreenGrass Deployments
- [ ] When updating the model, should create new version of the deployment
- [ ] Edge Modules should be represented as Greengrass components
- [ ] Components should be unique per model (use the device model id or name in the component name)
- [ ] Skip configuration of module commands and module twin settings
- [ ] Skip System modules
- [ ] Use AWS configuration to authenticate to ECR
- [ ] The deployment should target device group (use the dynamic group created for this model) - see: #1869

See [https://docs.aws.amazon.com/greengrass/v2/developerguide/run-docker-container.html#run-docker-container-requirements]

### Tasks

- [x] #2068
- [x] #2069
- [x] #2070
- [x] #2071
- [x] #2072
- [x] #2073

**Comment by inkonito** [comment]
@hocinehacherouf @kbeaugrand we'll need this story to be more detailed in order for us to start working on it

**Comment by kbeaugrand** [comment]
> @hocinehacherouf @kbeaugrand we'll need this story to be more detailed in order for us to start working on it

@inkonito do we need a PBR on that issue? 
if yes, @delager can you book a call on that topic with us?
