### ISSUE TITLE
Feature: UX improvements

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#398]
We did a UX review with our UX team, I will share with you what came out of it along with some priorities (to be discussed !) on each element. P1 = Most important, P2 = Important but we can live without it, P3 = Nice to have

I'd also like to say that nothing struck our team as a outright bad UX practices, so even if we have a lot of improvement suggestions, no need to worry 🙂

* General
    - [x] #783
    - [x] Grids with no elements should have an empty state with a message informing the user that there is no data to show. With no message, the user can expect content to still be loading or that there has been an error preventing data to arrive (P2)
    - [x] Grids should always be displayed while data is loading => Add the loader animation in the grid instead of displaying the grid after the data has been retrieved (P2)
    - [x] #617
    - [x] #785
    - [x] #786
    - [x] "Save" buttons should never be on the right side of the screen, always on the left or centered (P2) #425 

* Menu
    - [x] #402
    - [x] #420

* Devices list
    - [x] #421
    - [x] Pagination should be handled server-side, not client-side (P1)
       - #312 
       - #313
       - #314
    - [x] #422
    - [x] #484

* Device details
    - [x] #423
    - [x] #614
    - [x] #425
    - [ ] ~~Remove tabs, use collapsible cards instead (fixes the previous point) (P2)~~
    - [x] Rename "Status" to "Allowed" (clearer to the end user) (P3) tracked in #425 
    - [x] #485
    - [x] #424
    - [x] #615
    - [x] Save button in the left column global to the whole device details (P1) tracked in #425 

* Device creation
    - [x] #616
